apiVersion: v1
kind: ServiceAccount
metadata:
  name: aodsipam
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aodsipam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aodsipam-cni
subjects:
- kind: ServiceAccount
  name: aodsipam
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aodsipam-cni
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups: ["k8s.cni.cncf.io"]
  resources:
    - network-attachment-definitions
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
    - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipclaims/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ipclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal3.io
  resources:
  - ippools/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.metal3.io
  resources:
  - ippools/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aodsipam
  namespace: kube-system
  labels:
    tier: node
    app: aodsipam
spec:
  selector:
    matchLabels:
      name: aodsipam
  template:
    metadata:
      labels:
        tier: node
        app: aodsipam
        name: aodsipam
    spec:
      hostNetwork: true
      serviceAccountName: aodsipam
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: aodsipam
        command: [ "/bin/sh" ]
        args:
          - -c
          - >
            SLEEP=true /install-cni.sh
        image: localhost/aodsipam:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: AODSIPAM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: cni-net-dir
          mountPath: /host/etc/cni/net.d
        - name: cni-tmp
          mountPath: /tmp
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cni-tmp
          hostPath:
            path: /tmp
