---
apiVersion: v1
kind: Pod
metadata:
  name: testpod21
  annotations:
    k8s.v1.cni.cncf.io/networks: default/aodsipam-conf
spec:
  containers:
  - name: appcntr21
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]